### ISSUE TITLE
traitecoevo.github.io

### ISSUE THREAD

**Issue by dfalster** [jperkel/Science-on-GitHub#7]
Hi @jperkel 

Thanks for the great writeup. In addition to the Biomass and Allometry Database, we have some other  projects, including more datasets, R packages and reproducible analyses at traitecoevo.github.io, in case you want to add them to your list.  With best wishes, Daniel

**Comment by jperkel** [comment]
Thanks, Daniel! Can you add the suggested resources in a pull request? ~Jeff

**Comment by dfalster** [comment]
Sent via #9
